const types = {
    SET_ORDER : 'SET_ORDER',
    SET_MESSAGES: 'SET_MESSAGES',
    SET_CHANNEL: 'SET_CHANNEL',
    SET_CLIENT: 'SET_CLIENT',
    SET_USER: 'SET_USER',
    SET_PLACES: 'SET_PLACES',
    SET_THINGS_TO_DO: 'SET_THINGS_TO_DO',
    SET_RESTAURANTS_RECOMMENDATION: 'SET_RESTAURANTS_RECOMMENDATION',
    SET_ITINERARY_PLAN: 'SET_ITINERARY_PLAN',
    SET_SUGITIN_BY_CODE: 'SET_SUGITIN_BY_CODE',
    FORCE_LOADING_END: 'FORCE_LOADING_END',
    LOGOUT: 'LOGOUT'
}

export default types